git:
  depth: 1000
branches:
  only:
  - master
notifications:
  email: false
sudo: required
before_install:
- echo "deb http://us.archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- wget https://github.com/dgoodwin/tito/archive/tito-0.4.18-1.tar.gz -O /tmp/tito.tar.gz
install:
- sudo apt-get install yum yum-utils mock pigz python-rpm python-openssl python-urlgrabber python-decoratortools python-lzma python-setuptools python-krbv
- sudo pip install /tmp/tito.tar.gz
- sudo groupadd mock
- sudo usermod -a -G mock travis
before_script:
- sudo pwd
- sudo cp travis/mock/centos-6-x86_64.cfg /etc/mock/
- mkdir -p .tito/custom
script: travis/build
