#!/usr/bin/env bash

LOOKASIDE="http://koji.spacewalkproject.org/kojifiles/lookaside-static"

STATUS_ALL=0

GITROOT=$(pwd)/$(git rev-parse --show-cdup)

# For pull requests just compare target branch and github merge commit,
# TRAVIS_COMMIT_RANGE is unusable because there is commit from master
# and if pull request modifies old version, range is big and many files
# differ (may be bug in travis)
if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
else
    COMMIT_RANGE=$TRAVIS_BRANCH...FETCH_HEAD
fi

echo "Commit range: $COMMIT_RANGE"

CHANGED_FILES=$(git diff --name-only $COMMIT_RANGE | egrep "\.spec$")

for SPEC_FILE in $CHANGED_FILES ; do
  echo $SPEC_FILE
done
cd specs/tmux
#spectool -g -R tmux.spec
#rpmbuild -bs tmux.spec --nodeps
tito tag --keep-version --no-auto-changelog
ls -al
tito build --test --srpm --always
echo -en "travis_fold:start:$SPEC_FILE-build\\r"
sudo mock init -r centos-6-x86_64 --resultdir=~/mock/
echo -en "travis_fold:end:$SPEC_FILE-build\\r"
